disallowed-methods = [
    { path = "std::slice::from_raw_parts", reason = "see null_safe_slice" }
]
allow-mixed-uninlined-format-args = false
allow-unwrap-in-tests = true
allow-dbg-in-tests = true
pass-by-value-size-limit = 16
