disallowed-methods = [
    { path = "std::slice::from_raw_parts", reason = "see null_safe_slice" }
]
disallowed-macros = [
    { path = "std::dbg" }
]
allow-mixed-uninlined-format-args = false
allow-unwrap-in-tests = true
allow-dbg-in-tests = true
avoid-breaking-exported-api = false # We have one consumer and can afford to break the API.
pass-by-value-size-limit = 32
doc-valid-idents = ["HyStart", ".."]
