[package]
name = "neqo-client"
version = "0.4.26"
authors = ["Martin Thomson <mt@lowentropy.net>",
	"Dragana Damjanovic <dragana.damjano@gmail.com>",
	"Andy Grover <agrover@mozilla.com>"]
edition = "2018"
license = "MIT/Apache-2.0"

[dependencies]
neqo-crypto = { path = "./../neqo-crypto" }
neqo-transport = { path = "./../neqo-transport" }
neqo-common = { path="./../neqo-common" }
neqo-http3 = { path = "./../neqo-http3" }
neqo-qpack = { path = "./../neqo-qpack" }
structopt = "0.3.7"
url = "1.7.2"
qlog = "0.4.0"

[features]
default = ["deny-warnings"]
deny-warnings = []
