[package]
name = "neqo-client"
version = "0.7.0"
authors = ["Martin Thomson <mt@lowentropy.net>",
	"Dragana Damjanovic <dragana.damjano@gmail.com>",
	"Andy Grover <agrover@mozilla.com>"]
edition = "2018"
rust-version = "1.70.0"
license = "MIT OR Apache-2.0"

[dependencies]
mio = "~0.6.23"
neqo-common = { path="./../neqo-common" }
neqo-crypto = { path = "./../neqo-crypto" }
neqo-http3 = { path = "./../neqo-http3" }
neqo-qpack = { path = "./../neqo-qpack" }
neqo-transport = { path = "./../neqo-transport" }
qlog = { git = "https://github.com/cloudflare/quiche", rev = "09ea4b244096a013071cfe2175bbf2945fb7f8d1" }
structopt = "0.3"
url = "~2.5.0"

[features]
deny-warnings = []
