[package]
name = "neqo-client"
version = "0.6.6"
authors = ["Martin Thomson <mt@lowentropy.net>",
	"Dragana Damjanovic <dragana.damjano@gmail.com>",
	"Andy Grover <agrover@mozilla.com>"]
edition = "2018"
rust-version = "1.65.0"
license = "MIT OR Apache-2.0"

[dependencies]
neqo-crypto = { path = "./../neqo-crypto" }
neqo-transport = { path = "./../neqo-transport" }
neqo-common = { path="./../neqo-common" }
neqo-http3 = { path = "./../neqo-http3" }
neqo-qpack = { path = "./../neqo-qpack" }
structopt = "0.3.7"
url = "2.0"
qlog = "0.9.0"

[features]
deny-warnings = []
