[package]
name = "neqo-client"
authors = [
	"Martin Thomson <mt@lowentropy.net>",
	"Dragana Damjanovic <dragana.damjano@gmail.com>",
	"Andy Grover <agrover@mozilla.com>",
]
homepage.workspace = true
repository.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
futures = "0.3"
log = { version = "0.4.17", default-features = false }
neqo-common = { path = "./../neqo-common" }
neqo-crypto = { path = "./../neqo-crypto" }
neqo-http3 = { path = "./../neqo-http3" }
neqo-qpack = { path = "./../neqo-qpack" }
neqo-transport = { path = "./../neqo-transport" }
qlog = "0.12.0"
structopt = "0.3"
tokio = { version = "1", features = ["net", "time", "macros", "rt", "rt-multi-thread"] }
url = "~2.5.0"

[features]
deny-warnings = []
