[package]
name = "neqo-client"
version = "0.1.0"
authors = ["Martin Thomson <mt@lowentropy.net>",
	"Dragana Damjanovic <dragana.damjano@gmail.com>",
	"Andy Grover <agrover@mozilla.com>"]
edition = "2018"

[dependencies]
neqo-crypto = { version = "0.1", path = "./../neqo-crypto" }
neqo-transport = { version = "0.1", path = "./../neqo-transport" }
neqo-common = { version="0.1", path="./../neqo-common" }
neqo-http3 = { version = "0.1", path = "./../neqo-http3" }
structopt = "0.2.15"
url = "1.7.2"
