version: 2

jobs:
  build:
    docker:
      - image: martinthomson/neqo:latest
    working_directory: /home/neqo/neqo
    environment:
      NSS_JOBS: 3
      LD_LIBRARY_PATH: /home/neqo/dist/Debug/lib
      RUST_BACKTRACE: 1

    steps:
      - checkout

      - run:
          name: Show Versions
          command: |
            rustup show
            rustup --version
            rustc --version
            cargo --version
            rustfmt --version
            cargo clippy --version

      - restore_cache:
          name: "Restoring cache - Git"
          keys:
            - v1-git-{{ .Branch }}-{{ .Revision }}
            - v1-git-{{ .Branch }}
            - v1-git-main
            - v1-git-

      - restore_cache:
          name: "Restoring cache - NSS and NSPR"
          keys:
            - v1-nss-nspr-{{ epoch }}
            - v1-nss-nspr-

      # Workaround for https://discuss.circleci.com/t/22437
      - run:
          name: Tag Checkout
          command: |
            if [ -n "$CIRCLE_TAG" ] && [ -d .git ]; then
              remote=$(echo "$CIRCLE_REPOSITORY_URL" | \
                       sed -e 's,/^git.github.com:,https://github.com/,')
              git fetch -f "$remote" "refs/tags/$CIRCLE_TAG:refs/tags/$CIRCLE_TAG" || \
                (echo 'Removing .git cache for tag build'; rm -rf .git)
            fi

      - run:
          name: Update NSS/NSPR
          command: |
            hg -R "$NSS_DIR" pull -u
            hg -R "$NSPR_DIR" pull -u
            "$NSS_DIR"/build.sh -j "$NSS_JOBS" --static -Ddisable_tests=1

      - run:
          name: Check Formatting
          command: cargo fmt -- --check

      - run:
          name: Build
          command: cargo build -v --all-targets --tests

      - run:
          name: Clippy
          command: cargo clippy -v --all-targets --tests

      - run:
          name: Unit Tests
          command: cargo test -v

      - run:
          name: Command-line Utilities
          command: |
            set -e; spid=""; \
            trap '[ -z "$spid" ] || kill -9 "$spid"' EXIT; \
            cargo run --bin neqo-server -- '0.0.0.0:4433' & spid=$!; \
            cargo run --bin neqo-client -- 'https://127.0.0.1:4433/'

      - run:
          name: Internal Errors Check
          command: |
            all_internal_errors=($(find . -name '*.rs' -print | xargs -I {} sed '/Error::\(InternalError\|HttpInternal(\)/s/.*\(Error::[a-zA-Z]*([0-9]*)\)/\1/')); \
            unique_internal_errors=($(for e in "${all_internal_errors[@]}"; do echo "$e"; done | sort | uniq)); \
            [[ "${#all_internal_errors[@]}" -eq "${#unique_internal_errors[@]}" ]]

      - run:
          name: "Prepare for Caching"
          command: "git gc --auto"

      - save_cache:
          name: "Saving Cache - Git"
          key: v1-git-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/neqo/.git

      - save_cache:
          name: "Saving Cache - NSS and NSPR"
          key: v1-nss-nspr-{{ epoch }}
          paths:
            - ~/nss
            - ~/nspr
            - ~/dist
