[package]
name = "neqo-server"
version = "0.1.7"
authors = ["Martin Thomson <mt@lowentropy.net>"]
edition = "2018"
license = "MIT/Apache-2.0"

[dependencies]
neqo-crypto = { path = "./../neqo-crypto" }
neqo-transport = { path = "./../neqo-transport" }
neqo-common = { path="./../neqo-common" }
structopt = "0.2.15"
regex = "1"

[features]
default = ["deny-warnings"]
deny-warnings = []
