[package]
name = "neqo-server"
version = "0.1.0"
authors = ["Martin Thomson <mt@lowentropy.net>"]
edition = "2018"

[dependencies]
neqo-crypto = { version = "0.1", path = "./../neqo-crypto" }
neqo-transport = { version = "0.1", path = "./../neqo-transport" }
neqo-common = { version="0.1", path="./../neqo-common" }
structopt = "0.2.15"
