[package]
name = "neqo-interop"
version = "0.5.5"
authors = ["EKR <ekr@rtfm.com>"]
edition = "2018"
license = "MIT/Apache-2.0"

[dependencies]
neqo-crypto = { path = "./../neqo-crypto" }
neqo-transport = { path = "./../neqo-transport" }
neqo-common = { path="./../neqo-common" }
neqo-http3 = { path = "./../neqo-http3" }
neqo-qpack = { path = "./../neqo-qpack" }

structopt = "0.3.7"
lazy_static = "1.3.0"

[features]
default = ["deny-warnings"]
deny-warnings = []
