[package]
name = "neqo-interop"
version = "0.6.8"
authors = ["EKR <ekr@rtfm.com>"]
edition = "2018"
rust-version = "1.70.0"
license = "MIT OR Apache-2.0"

[dependencies]
neqo-crypto = { path = "./../neqo-crypto" }
neqo-transport = { path = "./../neqo-transport" }
neqo-common = { path="./../neqo-common" }
neqo-http3 = { path = "./../neqo-http3" }
neqo-qpack = { path = "./../neqo-qpack" }

structopt = "0.3.26"
lazy_static = "1.4.0"

[features]
deny-warnings = []
