[package]
name = "neqo-interop"
version = "0.1.5"
authors = ["EKR <ekr@rtfm.com>"]
edition = "2018"
license = "MIT/Apache-2.0"

[dependencies]
neqo-crypto = { version = "0.1", path = "./../neqo-crypto" }
neqo-transport = { version = "0.1", path = "./../neqo-transport" }
neqo-common = { version="0.1", path="./../neqo-common" }
neqo-http3 = { version = "0.1", path = "./../neqo-http3" }

structopt = "0.2.15"
