# In this file, every section corresponds to a header file.
# A corresponding binding file will be created in $OUT_DIR.

[nss_ssl]
types = [
    "PRUint16",
    "PRUint64",
    "PRUint8",
    "SECStatus",
    "SSLAeadContext",
    "SSLProtocolVariant",
    "SSLResumptionTokenCallback",
    "SSLSecretCallback",
    "SSLRecordWriteCallback",
]
functions = [
    "SSL_AuthCertificateComplete",
    "SSL_AuthCertificateHook",
    "SSL_CipherPrefSet",
    "SSL_ConfigServerCert",
    "SSL_ConfigServerSessionIDCache",
    "SSL_GetChannelInfo",
    "SSL_GetExperimentalAPI",
    "SSL_GetImplementedCiphers",
    "SSL_GetNextProto",
    "SSL_GetNumImplementedCiphers",
    "SSL_GetPreliminaryChannelInfo",
    "SSL_ForceHandshake",
    "SSL_ImportFD",
    "SSL_NamedGroupConfig",
    "SSL_OptionGet",
    "SSL_OptionSet",
    "SSL_PeerCertificateChain",
    "SSL_ResetHandshake",
    "SSL_SetNextProtoNego",
    "SSL_SetURL",
    "SSL_VersionRangeSet",
]
enums = [
    "SSLAuthType",
    "SSLCipherAlgorithm",
    "SSLCompressionMethod",
    "SSLContentType",
    "SSLKEAType",
    "SSLMACAlgorithm",
    "SSLNamedGroup",
    "SSLNextProtoState",
    "SSLProtocolVariant",
    "SSLSecretDirection",
    "SSLSignatureScheme",
    "SECStatus",
]
variables = [
    "SSL_LIBRARY_VERSION_.*",
    "SSL_NumImplementedCiphers",
    "ssl_preinfo_.*",
]
opaque = [
    "CERTCertificate",
    "PK11SymKey",
    "PLArenaPool",
    "PRFileDesc",
    "SECKEYPrivateKey",
    "SECKEYPublicKey",
    "SSLExtraServerCertData",
]

[nss_sslopt]
variables = [
    "SSL_REQUEST_CERTIFICATE",
    "SSL_REQUIRE_CERTIFICATE",
    "SSL_NO_LOCKS",
    "SSL_ENABLE_SESSION_TICKETS",
    "SSL_ENABLE_OCSP_STAPLING",
    "SSL_ENABLE_ALPN",
    "SSL_ENABLE_EXTENDED_MASTER_SECRET",
    "SSL_ENABLE_SIGNED_CERT_TIMESTAMPS",
    "SSL_ENABLE_0RTT_DATA",
    "SSL_RECORD_SIZE_LIMIT",
    "SSL_ENABLE_TLS13_COMPAT_MODE",
    "SSL_ENABLE_HELLO_DOWNGRADE_CHECK",
]

[nss_ciphers]
variables = [
    "TLS_AES_128_GCM_SHA256",
    "TLS_AES_256_GCM_SHA384",
    "TLS_CHACHA20_POLY1305_SHA256",
]

[nss_secerr]
types = ["SECErrorCodes"]
enums = ["SECErrorCodes"]

[nss_sslerr]
types = ["SSLErrorCodes"]
enums = ["SSLErrorCodes"]

[nss_init]
functions = [
    "NSS_Initialize",
    "NSS_IsInitialized",
    "NSS_NoDB_Init",
    "NSS_SetDomesticPolicy",
    "NSS_Shutdown",
]
variables = [
    "NSS_INIT_READONLY",
    "SECMOD_DB",
]

[nss_p11]
types = ["SECItem", "CK_ULONG"]
functions = [
    "CERT_DestroyCertificate",
    "PK11_Encrypt",
    "PK11_ExtractKeyValue",
    "PK11_FindCertFromNickname",
    "PK11_FindKeyByAnyCert",
    "PK11_FreeSlot",
    "PK11_FreeSymKey",
    "PK11_GetInternalSlot",
    "PK11_GetKeyData",
    "PK11_GetMechanism",
    "PK11_ImportSymKey",
    "PK11_ReferenceSymKey",
    "SECKEY_DestroyPrivateKey",
]
enums = [
    "PK11Origin",
    "SECItemType",
]
opaque = [
    "CERTCertificate",
    "PK11SlotInfo",
    "PK11SymKey",
    "SECKEYPublicKey",
    "SECKEYPrivateKey",
]
variables = [
    "CKA_DERIVE",
    "CKM_AES_ECB",
    "CKM_AES_GCM",
    "CKM_NSS_CHACHA20_POLY1305",
    "CKM_NSS_HKDF_SHA256",
    "CKM_NSS_HKDF_SHA384",
]

[nspr_err]
# NSPR doesn't use an enum for errors, so we have to pull in everything in the header file.
# Specifying no types, functions, or variables does that, but then exclude some.
exclude = [
    "nspr_.*",
    "PR_MAX_ERROR",
    "ERROR_TABLE_BASE_nspr"
]

[nspr_error]
functions = [
    "PR_ErrorToName",
    "PR_ErrorToString",
    "PR_GetError",
    "PR_SetError",
]
variables = [
    "PR_LANGUAGE_I_DEFAULT",
]

[nspr_io]
types = ["PRIOMethods"]
functions = [
    "PR_CreateIOLayerStub",
    "PR_GetUniqueIdentity",
    # These aren't being used yet.
    # "PR_Read",
    # "PR_Write",
]
variables = [
    "PR_AF_INET",
]
# opaque is for the stuff we don't plan to use, but we need for function signatures.
opaque = [
    "PRFileInfo",
    "PRFileInfo64",
    "PRFilePrivate",
    "PRIOVec",
    "PRSendFileData",
]
enums = [
    "PRDescType",
    "PRStatus",
    "PRSeekWhence",
    "PRSockOption",
    "PRTransmitFileFlags",
]
