name: bencher.dev Archive PR

on:
  pull_request_target:
    # SAFETY: We are not running any code from the triggering PR, so this is safe.
    types: [closed] # zizmor: ignore[dangerous-triggers]

permissions:
  contents: read

jobs:
  bencher_archive:
    name: Archive bencher.dev PR branch
    runs-on: ubuntu-24.04
    env:
      BENCHER_PROJECT: neqo
      BENCHER_API_TOKEN: ${{ secrets.BENCHER_API_TOKEN }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: bencherdev/bencher@v0.5.2 # zizmor: ignore[unpinned-uses]
      - run: bencher archive --branch "$GITHUB_HEAD_REF"
