name: bencher.dev Archive PR

on:
  pull_request_target:
    # SAFETY: We are not running any code from the triggering PR, so this is safe.
    types: [closed] # zizmor: ignore[dangerous-triggers]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  bencher_archive:
    name: Archive bencher.dev PR branch
    runs-on: ubuntu-24.04
    env:
      BENCHER_PROJECT: neqo
      BENCHER_API_TOKEN: ${{ secrets.BENCHER_API_TOKEN }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - uses: bencherdev/bencher@v0.5.8 # zizmor: ignore[unpinned-uses]
      - run: bencher archive --branch "$GITHUB_HEAD_REF"
