name: "Update CI Docker Image"

on:
  push:
    paths:
    - "ci/**"

jobs:
  build:
    name: "Update CI Docker Image"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: "Get Tag"
      id: tag
      run: |
        ref="${{ github.ref }}"
        if [ "$ref" = "refs/heads/master" ]; then
          echo "::set-output name=tag::latest"
        elif [ "${ref#refs/tags/}" != "$ref" ]; then
          echo "::set-output name=tag::${ref#refs/tags/}"
        else
          echo "::set-output name=tag::"
        fi

    - name: "Publish Latest"
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: neqoquic/ci
        path: ci
        tags: ${{ steps.tag.outputs.tag }}
        push: ${{ steps.tag.outputs.tag != '' }}
