name: Fuzz & Bench
on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  fuzz-bench:
    name: Check that the fuzz and bench targets work
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-15] # FIXME: ubuntu-24.04-arm has issues
        check: [fuzz, bench]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: ./.github/actions/rust
        with:
          version: nightly
          tools: ${{ matrix.check == 'fuzz' && 'cargo-fuzz' || ''}}
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/actions/nss

      - if: ${{ matrix.check == 'fuzz' }}
        env:
          UBUNTU: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: |
          cargo fuzz build --dev
          for fuzzer in $(cargo fuzz list); do
            cargo fuzz run --dev --sanitizer none "$fuzzer" -- -runs=1
          done

      - if: ${{ matrix.check == 'bench' }}
        run: cargo bench --features bench --profile dev --  --profile-time 1
